### ISSUE TITLE
run-jetty doesn't accept vars as handlers

### ISSUE THREAD

**Issue by hiredman** [sunng87/ring-jetty9-adapter#102]
using with-meta like this https://github.com/sunng87/ring-jetty9-adapter/blob/master/src/ring/adapter/jetty9/handlers/sync.clj#L19 to attach metadata to a handler the definition of a handler from any functions (something that implements IFn) to functions that you can use with-meta with (implements IObj and IFn).

Vars don't implement IObj but do implement IFn, and it has been a common idiom to use a var as a ring handler to allow re-definition of the handler at the repl.

Additionally using with-meta to add metadata to a function essential wraps the function in something like `(fn [ & args] (apply f args))` with the varargs performance hit (which is admittedly small and may get swamped by io overheads in a webserver)

**Comment by sunng87** [comment]
Sounds reasonable. I will find time to resolve this. If you are interested in a PR for this, it's welcomed
