### ISSUE TITLE
Jetty 12 adoption

### ISSUE THREAD

**Issue by sunng87** [sunng87/ring-jetty9-adapter#105]
Jetty 12 has been released: https://github.com/eclipse/jetty.project/releases/tag/jetty-12.0.0

**Comment by jasonjckn** [comment]
@sunng87 Am very interested in this release due to improved vthreads architecture. 

I'm not sure if i'm in a position to offer help, but i'm curious do you need help or are you just going to tackle this yourself?

**Comment by sunng87** [comment]
Nice. My bandwidth has been pretty limited these so help is welcomed! 

At the moment we don't rely on any javax or jarkata api. So if I understand correctly we are already fully rely on the lower level API. Maybe it's still possible to remove anything servlet like `org.eclipse.jetty.servlet.ServletContextHandler`

**Comment by jasonjckn** [comment]
Yah, removing Servlet is what I meant by that. 

>  lazy-seq/synchronized usage to see the benefit?
Hard to say whether it'll be that noticeable, you'd to do some pretty hard core benchmarks I think, but this is the advice given for using virtual threads. 

---

Assuming we're dropping Servlet, would it make more sense to create a new project, namely `ring-jetty12-adapter` and just keep everything disentangled, you probably won't be be able to keep the exact same API, and the dependencies are obviously very different, some people may still want jetty 11 support with servlet.

**Comment by sunng87** [comment]
We are in 0.x release so I think breaking changes are allowed. We can keep jetty 11 version on a branch and maintain it until its EOL.

On API wise we don't expose anything related to servlet. The ring spec and our websocket extension are all neutral. So I think there is a good chance we can keep the API from breaking changes.

**Comment by joakime** [comment]
> So if I understand correctly we are already fully rely on the lower level API. Maybe it's still possible to remove anything servlet like `org.eclipse.jetty.servlet.ServletContextHandler`.

If you use jetty-core stuff, you can completely eliminate Servlet dependencies and behaviors.

**Comment by sunng87** [comment]
hmmm, just got time to check the code again we are using `jakarta.servlet` packages although the `project.clj` doesn't tell.

**Comment by jasonjckn** [comment]
https://github.com/sunng87/ring-jetty9-adapter/pull/111
