### ISSUE TITLE
Jetty 11.0.18

### ISSUE THREAD

**Issue by seancorfield** [sunng87/ring-jetty9-adapter#119]
We're blocked on moving to Jetty 12 (awaiting official support from New Relic) so we're trying to keep things up-to-date on Jetty 11.

11.0.18 is available with some good bug fixes, if you feel inclined to do another 0.22.x maintenance release?

**Comment by sunng87** [comment]
Hi @seancorfield , it was released as `0.22.4`. I will keep jetty-11 branch maintained for some time. I forgot to create github release for that version. Let me know if there is any problem.

**Comment by seancorfield** [comment]
Thank you!
