### ISSUE TITLE
Websocket config

### ISSUE THREAD

**Issue by eneroth** [sunng87/ring-jetty9-adapter#124]
I would like to configure [setMaxBinaryMessageSize](https://eclipse.dev/jetty/javadoc/jetty-12/org/eclipse/jetty/websocket/common/WebSocketSession.html#setMaxBinaryMessageSize(long)) and [setMaxFrameSize](https://eclipse.dev/jetty/javadoc/jetty-12/org/eclipse/jetty/websocket/common/WebSocketSession.html#setMaxFrameSize(long)) for websockets. Would it be possible to get access to them. Or to fully generalize, maybe take a lambda that can flip arbitrary switches?

**Comment by sunng87** [comment]
Sounds good to me. And in additional to #125, I'm going to add option for `max-binary-message-size` and `max-frame-size` as well.
