### ISSUE TITLE
`:wrap-jetty-handler` option no longer has any effect since 0.30/Jetty 12

### ISSUE THREAD

**Issue by svdm** [sunng87/ring-jetty9-adapter#128]
I've found the `:wrap-jetty-handler` to be very handy for wrapping the app handler created by the adapter in one or more Jetty handlers. However, in the current release the option is never used, though it is still listed and destructured in `run-jetty`. This seems to have happened in the changes required for Jetty 12, ie. 0.30.0.

Is it feasible to restore this functionality or is there a better way to do this in Jetty 12?

**Comment by sunng87** [comment]
This was a mistake/regression when upgrading to jetty 12. I'm adding #130 to bring it back.

**Comment by sunng87** [comment]
Released in 0.32.3
