### ISSUE TITLE
HTTP/2 Cookies are unintentionally truncated/removed

### ISSUE THREAD

**Issue by rmrt1n** [sunng87/ring-jetty9-adapter#136]
HTTP/2 allows for [multiple cookie header fields](https://www.rfc-editor.org/rfc/rfc7540#section-8.1.2.5). This results in the adapter removing cookies when there are multiple cookies in the request header.

This is the parsed request map in HTTP/1.1:

```clj
{:headers {"cookie" "Cookie-1=value; Cookie-2=value"}}
```

And in HTTP/2:

```clj
;; cookie 1 is removed because the key ("cookie") is the same
{:headers {"cookie" "Cookie-2=value"}}
```

A possible solution is to merge the cookie values:

```clj
;; src/ring/adapter/jetty9/common.clj

(defn- combine-headers
  ([] {})
  ([result] result)
  ([result [k v]]
   (if (and (= "cookie" k) (get result k))
     (update result k #(str % "; " v))
     (assoc result k v))))

(defn get-headers
  "Creates a name/value map of all the request headers."
  [^Request request]
  (transduce
   (map header-kv*)
   combine-headers
   {}
   (.getHeaders request)))
```

I haven't read the full HTTP/2 spec so there might be other header keys that could have multiple values. The above function works just for this specific case. 

Tested with the HTTP2 example and by setting multiple cookies in browser dev tools:

```clj
;; examples/rj9a/http2.clj
;; ...
(defn dummy-app [req]
  (println (get-in req [:headers "cookie"]))
  {:body "It works" :status 200})
;; ...
```

**Comment by sunng87** [comment]
I see. This is a feature we need to support. Can you send a pull request with your fix? It looks good to me.

**Comment by sunng87** [comment]
After a quick walk through of http/2 spec, I think cookie is the only header that has this behaviour defined.

**Comment by rmrt1n** [comment]
Cool, thanks for the quick response!
