### ISSUE TITLE
Configuring the Jetty thread pool

### ISSUE THREAD

**Issue by trptcolin** [sunng87/ring-jetty9-adapter#18]
Based on the advice on [this Jetty wiki about high load](https://wiki.eclipse.org/Jetty/Howto/High_Load#Thread_Pool), I'd like to be able to bound the number of incoming requests. Would you be interested in a patch to make it possible to configure the thread pool's backing queue?

**Comment by sunng87** [comment]
Currently only `:max-threads` is exposed as an option. We need more options to configure the `QueuedThreadPool` via options. 

javadoc:
http://download.eclipse.org/jetty/stable-9/apidocs/org/eclipse/jetty/util/thread/QueuedThreadPool.html

Patch is welcomed. Thanks!

**Comment by trptcolin** [comment]
Great, thanks - PR opened.

**Comment by sunng87** [comment]
Implemented in #19
