### ISSUE TITLE
No request-map or session context passed to Websocket functions

### ISSUE THREAD

**Issue by NoamB** [sunng87/ring-jetty9-adapter#25]
Hi, 

How do you know which user sent the text or binary message? Currently I see no request-map or session map passed into on-text and on-bytes (or any other WS function).

**Comment by sunng87** [comment]
From 0.9, you can retrieve the request map from ws with `(req-of ws)`. But it only contains base Ring request map without session information. 

https://github.com/sunng87/ring-jetty9-adapter/blob/master/src/ring/adapter/jetty9/websocket.clj#L59

**Comment by NoamB** [comment]
Thanks,
I think I can work with this (i.e. pass the result of (req-of ws) into my middleware stack to get the session again).
