### ISSUE TITLE
lein uberwar - websocket ? 

### ISSUE THREAD

**Issue by amitvshah25** [sunng87/ring-jetty9-adapter#29]
First of all, thanks for a great library ! This works great when running in my DEV environment. However in QA and PROD environments, we have a jetty running and several web-applications that need to run under that. I am trying the lein uberwar, but I am not able to figure out how to get the :websockets option that we pass to run-jetty - to be specified in uberwar .. ?

**Comment by sunng87** [comment]
hi @amitvshah25 , by creating a war package, you are deploying your application into a running jetty instance. However, this adapter uses embedded jetty to provide websocket via jetty apis.

I'm not sure if it's possible to use websocket from a war package. But at the moment it's not supported by this rj9a.
