### ISSUE TITLE
Ring handler for Websockets

### ISSUE THREAD

**Issue by yogthos** [sunng87/ring-jetty9-adapter#41]
Are there any plans to support a standard Ring handler for Websockets as seen in Immutant and HTTP Kit. For example, something along the lines of:

```clojure
(defn handler [request]
  (with-channel request channel
    {:on-connect (fn [ws])
     :on-error (fn [ws e])
     :on-close (fn [ws status-code reason])
     :on-text (fn [ws text-message])
     :on-bytes (fn [ws bytes offset len])}))
```

This would allow ws routes to be defined the same way regular routes are defined via standard routing libraries. The ws routes would then be able to share all the middleware such as sessions and authentications with the other routes in the application.

**Comment by sunng87** [comment]
For now WebSocket paths were defined separately because Jetty's API uses different handler for WebSocket and regular HTTP servlet requests. I'll look into other implementation to see possible solution.

**Comment by yogthos** [comment]
One idea might be to just chain the handlers internally. It looks like it's possible to update the `HandlerList` dynamically, so perhaps something like [this](https://github.com/sunng87/ring-jetty9-adapter/blob/08de8d1cde171ad44d56ae668ad6092d42ea30b6/src/ring/adapter/jetty9.clj#L251) would be called on an incoming Ws request.

In the example above `with-channel` macro could handle Ws negtiation as needed and then call the body within the Ws context.

**Comment by robert-stuttaford** [comment]
+1 for this. It seems there is no way to use dynamic routing for WebSockets under the current implementation?

**Comment by yogthos** [comment]
I actually ended up making an implementation of that [here](https://github.com/luminus-framework/luminus-jetty/blob/9c7347aa3d68119f55f3e6abf00eaa56e538d4b8/src/luminus/http_server.clj#L10).

**Comment by sunng87** [comment]
Ring 2.0 seems to have such a section for websockets https://github.com/ring-clojure/ring/blob/2.0/SPEC-2.md#3-websockets

**Comment by yogthos** [comment]
yeah, looks like that's going to be part of the spec going forward

**Comment by awb99** [comment]
It wuld be really great if jetty couldhave the same api for websockets as httpkit, ...
Otherwise one can not switch between different webservers.
Also this would make it much easier to add jetty support for sente

**Comment by sunng87** [comment]
Actually I think you can use the same ring app for both main app and websocket path, too.  Just keep in mind your websocket path in the route should be consistent with the path specified in `(run-jetty)`

```clojure
(run-jetty app {:port 8080 :websockets {"/path1" app}})
```

**Comment by sunng87** [comment]
This is supported via #59 finally.
