### ISSUE TITLE
:server-name isn't present but :host is

### ISSUE THREAD

**Issue by robert-stuttaford** [sunng87/ring-jetty9-adapter#45]
Small issue in the ring request map that `:websockets` handlers receive; `:server-name` isn't present but `:host` is.

**Comment by sunng87** [comment]
`UpgradeRequest` https://www.eclipse.org/jetty/javadoc/9.4.28.v20200408/org/eclipse/jetty/websocket/api/UpgradeRequest.html

According to [Ring SPEC](https://github.com/ring-clojure/ring/blob/master/SPEC), we need to add keys:
* `:server-name`
* `:server-port`
* `:remote-addr`
* `:scheme`

In addition to these standard fields, I also want to make `subprotocols` and `extensions` available to user.
