### ISSUE TITLE
`run-jetty` never returning from join

### ISSUE THREAD

**Issue by dpetranek** [sunng87/ring-jetty9-adapter#49]
After running `ring.adapter.jetty9/run-jetty`, the function never returns.

Here's a minimal reproduction:

```clojure
(ns ring.adapter.foo
  (:require [ring.adapter.jetty9 :as http]))

(defn app [_] {:status 200 :body "functional"})

(comment
  (defonce server (http/run-jetty app {:port 50505}))
  (http/stop-server server)

  )
```

The server does start, but it apparently hangs while trying to join. I added some logging to `run-jetty` and confirmed that:

```
(defn ^Server run-jetty
  [handler {:as options
            :keys [max-threads websockets configurator join? async?
                   allow-null-path-info wrap-jetty-handler]
            :or {allow-null-path-info false
                 join? true
                 wrap-jetty-handler identity}}]
  (let [^Server s (create-server options)
        ring-app-handler (wrap-jetty-handler
                          (if async? (proxy-async-handler handler) (proxy-handler handler)))
        ws-handlers (map (fn [[context-path handler]]
                           (doto (ContextHandler.)
                             (.setContextPath context-path)
                             (.setAllowNullPathInfo allow-null-path-info)
                             (.setHandler (proxy-ws-handler handler options))))
                         websockets)
        contexts (doto (HandlerList.)
                   (.setHandlers
                    (into-array Handler (reverse (conj ws-handlers ring-app-handler)))))]
    (.setHandler s contexts)
    (when-let [c configurator]
      (c s))
    
    (println "before start") ; <- debug logging starts here
    (.start s)
    (println "after start")
    
    (println "before join")
    (when join?
      (.join s))
    (println "after join")
    
    s))
```

And this is what is logged:
```
before start
after start
before join
```

I'm not entirely sure what `join` is supposed to do, but it effectively prevents me from turning the server off without killing the whole jvm, which isn't ideal : )

**Comment by sunng87** [comment]
You can add option `:join? false` in `run-jetty` to disable this behaviour.

**Comment by dpetranek** [comment]
Thanks, that does resolve the issue. Seems like an awkward default for repl-oriented workflows, though. I'm not familiar with use cases that require blocking (and they may very well be sensible and I'm just ignorant), but I think it would be a good idea to add the `:join? false` entry to the config map in the examples.

Let me know if that's a good idea and I'd be happy to make a pull request.

**Comment by sunng87** [comment]
There is description for each option in docstring of `run-jetty`. I think in most case you will need `:join? true` when deploying this server on production. It prevents the main thread to exit.
