### ISSUE TITLE
Lazy behaviour for websocket `msg`?

### ISSUE THREAD

**Issue by refset** [sunng87/ring-jetty9-adapter#53]
I've found that this doesn't work due to laziness:
```clojure
(send! ws (str (some-custom-fn)))
```

Wrapping it in a `doall` seems to fix things:
```clojure
(send! ws (doall (str (some-custom-fn)))
```

Is that expected behaviour?

**Comment by sunng87** [comment]
Yes, this is expected. You need to use `doall` if `some-custom-fn` returns lazy seqs.
