### ISSUE TITLE
Supporting :keystore-scan-interval like the main Jetty adapter

### ISSUE THREAD

**Issue by TuggyNE** [sunng87/ring-jetty9-adapter#57]
Looks like Ring's bundled Jetty adapter supports a useful option, `:keystore-scan-interval`, which allows updating certificates without restarting the server. Seems like the code for it is pretty simple, although I haven't tried building from source yet so I don't have an easy way to test it. Thoughts on pulling that in?

**Comment by jimpil** [comment]
This is now supported (after merging #91), or rather, automatically happening so this ticket could be closed.

**Comment by jimpil** [comment]
@sunng87 Now that we rely on Jetty's `KeyStoreScanner`, it is trivial to support a `ssl-keystore-scan-interval` option, and propagate it down to the `.setScanInterval` call (which now hardcodes 3600). I would have done this in my PR, but I completely forgot about this issue... :(
