### ISSUE TITLE
`ws-upgrade-request?` doesn't always works.

### ISSUE THREAD

**Issue by niwinz** [sunng87/ring-jetty9-adapter#61]
Hi there!

I have noticed that using the new mechanism to upgrade to websockets connection does not works in all situations. The concrete case I found it using Firefox (I dind't noticed it until my coworker asked me, for some reason that endpoint does not works on firefox...)

The main cause is that `ws-upgrade-request?` is very strict on websocket connection detection. It works as expexted on Chrome and Brave but not in Firefox. 

The current impl looks this way:

```clojure
(defn ws-upgrade-request?
  "Checks if a request is a websocket upgrade request.
   It is a websocket upgrade request when it contains the following headers:
   - connection: upgrade
   - upgrade: websocket
  "
  [{:keys [headers] :as _request-map}]
  (let [headers (lower-case-keys headers)
        upgrade (get headers "upgrade")
        connection (get headers "connection")]
    (and upgrade
         connection
         (=ignore-case "websocket" upgrade)
         (=ignore-case "upgrade" connection))))
```

The function expects that `Connection` header only contain the `Upgrade` value, but Firefox for some reason sends `Connection: keep-alive, Upgrade`; and in this case, this function returns false negative and the following code does not upgrades to websocket.

We internally replaced the `ws-upgrade-request?` predicate with something like this:

```clojure
(defn ws-upgrade-request?
  [{:keys [headers]}]
  (let [upgrade    (get headers "upgrade")
        connection (get headers "connection")]
    (and upgrade
         connection
         (str/includes? (str/lower-case upgrade) "websocket")
         (str/includes? (str/lower-case connection) "upgrade"))))
```

Note that, I don't convert the headers map to lowercase keys because they [are already lowercased](https://github.com/ring-clojure/ring/blob/1.9.0/ring-servlet/src/ring/util/servlet.clj#L37) and we don't need to repeat the work.

Additionally, I also noted that in the `jetty9` ns, the private predicate `websocket-upgrade-response?` also does the redundant headers lowercasing. I think this function can be optimized for avoid doing duplicate work and unnecessary repetitive checks. 

My suggestion here is: as is expected that users use the `ws-upgrade-response` helper function, you can return something easy checkable with a simple condition instead checking the headers and status code in the `websocket-upgrade-response?`

I think something like this will be more than enough:

```clojure
(defn- websocket-upgrade-response?
  [{:keys [status ws]}]
  (and (= 101 status) ws))
```
Because the contract is, if you return status 101 and ws handler, this is a websocket upgrade... then, we don't need to make additional checks.

In any case, thanks for you work maintaining this package.

**Comment by niwinz** [comment]
If you are ok, with the proposed changes I can make the PR myself.

**Comment by sunng87** [comment]
Please make the PR. Thank you!
