### ISSUE TITLE
Removal of previous websocket configuration API a month after first introducing replacement makes upgrading hazardous

### ISSUE THREAD

**Issue by TuggyNE** [sunng87/ring-jetty9-adapter#72]
In 0.15.3, if I'm not mistaken, the only way to configure websockets was through the `:websockets` key in `options`. The next version, 0.16.0, introduced a new simplified API with `ws-upgrade-request?`/`ws-upgrade-response`, which is great! But then a month later 0.17.0 removed `:websockets` support entirely. Anyone who doesn't have the time to rewrite their server's websocket support is now stuck on an old version.

The rewrite probably seems pretty trivial for the base case, but for someone using a library that does non-trivial things with websocket support, such as [Sente](https://github.com/ptaoussanis/sente/blob/master/src/taoensso/sente/server_adapters/jetty9.clj), working out how to simplify the handshake so it works again is non-trivial, and of course expecting an unrelated library to adapt to breaking changes within a month would be silly. Putting the deprecated support back in for now to allow a longer transition would be appreciated.

**Comment by sunng87** [comment]
@TuggyNE Thank you for reaching out! Jetty and the adapter has been mature enough and there isn't much feature to be add in 0.17.x. So it's totally OK to stick with 0.16 until http/3 support or any security fix is out. I can offer help on porting Sente to newer release the library, and perhaps adding back the legacy api if the new one cannot fit features in Sente.
