### ISSUE TITLE
Jetty 11?

### ISSUE THREAD

**Issue by seancorfield** [sunng87/ring-jetty9-adapter#78]
I see changes being made to move to Jetty 11.0.12 which is great.

At work, we're about to move from Jetty 9 (and the reference Ring adapter) to Jetty 11 and your adapter -- so it seems my timing is good.

Do you have a release date in mind for the Jetty 11-based version? And are there any substantive changes I should be aware of if I go to 0.17.9 (and Jetty 10) first and then update when your Jetty 11 version appears?

**Comment by sunng87** [comment]
hello @seancorfield ! 0.18.0 has been released to clojars, which uses jetty 11 thanks to #77 from @sundbry . ASAIK, jetty 11 has exact features and apis except it use later version of servlet api. Unless you are using `javax.servlet` apis, or `ring.servlet` package from your code, you don't have to change anything to adapt jetty 11.

**Comment by sundbry** [comment]
Hi @seancorfield, for Jetty 10 you'll want to make sure you are at least on Java 11, and for Jetty 11, you'll want to double-check your deps to make sure no stray dependences are pulling in obsolete Jetty 9 code. Some of the maven packages for websockets have been renamed, so its possible you get some class loader issues if anything accidentally pulls that old code in.

**Comment by seancorfield** [comment]
@sundbry We're on JDK 18 in production and JDK 19 in dev/CI right now. We're using `deps.edn` so it always uses the most recent version it finds (unlike Leiningen) -- so I can guarantee we're using 11.0.12 since we've updated to 0.18.0 now.

Thank you!
