### ISSUE TITLE
ws-handler as function does not work

### ISSUE THREAD

**Issue by seancorfield** [sunng87/ring-jetty9-adapter#79]
ws-handler as a hash map works just fine.

ws-handler as a fn of upgrade-request fails (silently). I believe the problem is here:

```clojure
            (when-let [exts (not-empty (:extensions ws-results))]
              (.setExtensions resp (mapv #(JettyExtensionConfig. ^String %) exts)))
```

When I added debugging, `(:extensions ws-results)` is already a vector of `JettyExtensionConfig` objects like this:

```
[#object[org.eclipse.jetty.websocket.common.JettyExtensionConfig 0x60e1a703 permessage-deflate;client_max_window_bits]]
```

This is with the 0.17.9 release.

**Comment by seancorfield** [comment]
https://www.eclipse.org/jetty/javadoc/jetty-11/org/eclipse/jetty/websocket/api/UpgradeRequest.html#getExtensions()

Returns `List<ExtensionConfig>` not `List<String>` (which is what `getSubProtocols()` returns).

**Comment by sunng87** [comment]
Thank you for the investigation! Could you please send a pull request for this?

**Comment by seancorfield** [comment]
Should a vector of strings be acceptable for `:extensions`? Should both strings and config objects be acceptable? Should the `getExtensions` convert the config objects to strings? It's not clear to me what is intended or what would be the best approach for usability.

**Comment by sunng87** [comment]
I just created #80 to support both string and `ExtensionConfig`. I think there are scenarios for both. And for input, although giving `ExtensionConfig` object to clojure developer is not most friendly, it avoids `ExtensionConfig` -> `String` -> `ExtensionConfig` conversion in most cases.

**Comment by seancorfield** [comment]
That looks good, thanks! And thanks for the rationale for that choice too. Users could always call `.getParameterizedName()` on the config object if they need a string to decide what to do. I look forward to 0.18.1 with that fix.

**Comment by sunng87** [comment]
Thank you! 0.18.1 has been released on clojars.

**Comment by seancorfield** [comment]
Just updated to that version and removed our workaround -- seems to work great! Thanks for the speedy fix!
