### ISSUE TITLE
[DOCS] - Improve :thread-pool 

### ISSUE THREAD

**Issue by jimpil** [sunng87/ring-jetty9-adapter#81]
Hi there, 

Many thanks for keeping this alive and maintained 👍 ... 

Just a quick improvement here: 
The `:thread-pool` option (in the `run-jetty` doc-string) should mention that it expects an impl of [org.eclipse.jetty.util.thread.ThreadPool](https://www.eclipse.org/jetty/javadoc/jetty-11/org/eclipse/jetty/util/thread/ThreadPool.html) (per [this line](https://github.com/sunng87/ring-jetty9-adapter/blob/514da35c78a17cbb441ab7c1a00f885f80eaf503/src/ring/adapter/jetty9.clj#L249)), as someone might think that a regular Java one will do.

**Comment by sunng87** [comment]
Thank you! Just pushed e606b98 to address this.
