### ISSUE TITLE
:ssl-port  param documentation needs improving

### ISSUE THREAD

**Issue by jimpil** [sunng87/ring-jetty9-adapter#85]
Hi there,

I just stumbled on this - should be  a quick fix...basically, the doc-string for `:ssl-port` says that it defaults to 443, but that is only true for the `http-config` call - the call to `https-connector` also needs to default it. Currently, if you do pass `:ssl-port`, `ssl?` is inferred as true (exactly as the docs say), but if you do the opposite, i.e. pass `ssl?` true, the `ssl-port` is not inferred to be 443, and [this line](https://github.com/sunng87/ring-jetty9-adapter/blob/82c41070218c5090c924a9d92792abbc601689d0/src/ring/adapter/jetty9.clj#L207) ultimately fails.

**Comment by sunng87** [comment]
Thank you! I just created a fix in #87
