### ISSUE TITLE
Consider proxy-ing handlers in Java

### ISSUE THREAD

**Issue by jimpil** [sunng87/ring-jetty9-adapter#92]
I'm just throwing this out there because I noticed that `proxy-handler` (and its async cousin) uses `proxy`, which is rather slow. You would probably see more than a 10x speedup from replacing that with a Java shim. Looking at the implementation, I can see half of it is Java interop anyway!  There is a `proxy+` library out there, but I'm generally reluctant bringing in dependencies for something so simple. 

Just an idea 👍 

[edit]: a nice name for such a class would be `RingServletHandler` (extends `ServletHandler` obviously).

**Comment by sunng87** [comment]
That sounds good! I just checked `proxy+` and since `proxy` is on the critical invocation path I think it's worth to pull in additional dependencies for that improvement.

**Comment by jimpil** [comment]
Look, this is ultimately your decision. What I will say is that, even though `proxy+` looks solid, it comes with its own dependencies, including `spectre` (which in turn brings in `riddley` and so forth). If you (as the lib maintainer) don't mind this extra baggage, then sure, swapping vanilla `proxy` for `proxy+` sounds like a good option. I would personally avoid doing that, since we're talking about a single  type that we need - i.e it's not like there are a bunch of proxies that need replacing. Any other `proxy` usage can probably stay vanilla, and noone will notice.  

By the way, have you considered `gen-class`? I can provide sample code, or a PR if you want...

**Comment by sunng87** [comment]
`:gen-class` sounds like a better idea to me. I will be happy to merge a 
PR like that

**Comment by jimpil** [comment]
Ok, so here is a quick (untested) sketch: 

```clj
(ns ring.adapter.jetty9.handler
  (:require
    [ring.adapter.jetty9.common :as common]
    [ring.adapter.jetty9.servlet :as servlet]
    [ring.adapter.jetty9.websocket :as ws])
  (:import (jakarta.servlet.http HttpServletRequest HttpServletResponse)
           (org.eclipse.jetty.server Request))
  (:gen-class
    :name "ring.adapter.jetty9.handler.ProxyHandler"
    :extends org.eclipse.jetty.servlet.ServletHandler
    :state "ringHandler"
    :init "init"
    :constructors {[clojure.lang.IFn] []}
    :prefix "-"))

(defn -init
  [ring-handler]
  [[] ring-handler])

(defn -doHandle
  [this ^Request base-request ^HttpServletRequest request ^HttpServletResponse response]
  (try
    (let [handler      (.ringHandler this) ;; new code
          request-map  (common/build-request-map request)
          response-map (-> request-map handler normalize-response)]
      (when response-map
        (if (websocket-upgrade-response? response-map)
          (ws/upgrade-websocket request response (:ws response-map) options)
          (servlet/update-servlet-response response response-map))))
    (catch Throwable e
      (.sendError response 500 (.getMessage e)))
    (finally
      (.setHandled base-request true))))
```

I'll try to work more on it, after we merge #91
