### ISSUE TITLE
HTTP2/3 connector/factory specific options in server config

### ISSUE THREAD

**Issue by KsVlad** [sunng87/ring-jetty9-adapter#99]
Hi,

What do you think about adding some options specific to [AbstractHTTP2ServerConnectionFactory](https://www.eclipse.org/jetty/javadoc/jetty-11/org/eclipse/jetty/http2/server/AbstractHTTP2ServerConnectionFactory.html) and [QuicServerConnector](https://www.eclipse.org/jetty/javadoc/jetty-11/org/eclipse/jetty/quic/server/QuicServerConnector.html) and not listed in [HttpConfiguration](https://www.eclipse.org/jetty/javadoc/jetty-11/org/eclipse/jetty/server/HttpConfiguration.html) to the top-level run-jetty config?

Personally I'm interested in [setMaxConcurrentStreams](https://www.eclipse.org/jetty/javadoc/jetty-11/org/eclipse/jetty/http2/server/AbstractHTTP2ServerConnectionFactory.html#setMaxConcurrentStreams(int)) at the moment. But if you find it interesting to add some set of options, I could make a PR.

There is a run-jetty's :configurator option of course, but ConnectionFactory and Connector mentioned above end up deep in the guts of server, so I thought it's worth to ask.

So, what is your opinion? Please, feel free to won't fix it :)

**Comment by sunng87** [comment]
Sounds good to me! Please make your PR for that, thank you!

**Comment by KsVlad** [comment]
Here it is for http2 https://github.com/sunng87/ring-jetty9-adapter/pull/100

**Comment by KsVlad** [comment]
For http3 I see two specific places for configuration: [HTTP3Configuration](https://www.eclipse.org/jetty/javadoc/jetty-11/org/eclipse/jetty/http3/HTTP3Configuration.html) on HTTP3ServerConnectionFactory and [QuicConfiguration](https://www.eclipse.org/jetty/javadoc/jetty-11/org/eclipse/jetty/quic/common/QuicConfiguration.html) on HTTP3ServerConnector. At least it's touched in the [docs](https://www.eclipse.org/jetty/documentation/jetty-11/programming-guide/index.html#pg-server-http3-setup).

There are no common names in setters, so I think a collective option like :h3-options could be used for both.

Hope next time will go smoothly, cause we already agreed on shape :)

**Comment by sunng87** [comment]
Thank you! Just checked these two configurations I think it's OK to merge them into a single map.

**Comment by KsVlad** [comment]
http3 https://github.com/sunng87/ring-jetty9-adapter/pull/101

**Comment by KsVlad** [comment]
Seems like all done here

**Comment by sunng87** [comment]
@KsVlad Thank you very much. I will create a release later to include these changes.

**Comment by KsVlad** [comment]
Thank you for this gem :)
